### ISSUE TITLE
missing import statements

### ISSUE THREAD

**Issue by georgeAccnt-GH** [Azure-Samples/storage-python-manage#6]
basic example in https://github.com/Azure-Samples/storage-python-manage/blob/master/README.md (also surfaced at https://azure.microsoft.com/en-us/resources/samples/storage-python-manage/) will __not__ work without this:   
from azure.mgmt.storage.models import Sku, SkuName, Kind

**Comment by berndverst** [comment]
It appears that this fixed long ago. Thanks for flagging it.
